name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}} << 'EOF'
          cd ~/projects/Office-ai/
          git pull origin main
          echo "Setting up Python virtual environment..."
          rm -rf venv || echo "Failed to remove venv. Check permissions."
          python3.10 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install gunicorn
          pip install -r requirements.txt
          echo "Restarting Flask application with Gunicorn..."
          PID=$(lsof -ti:5001) && [ -n "$PID" ] && kill -9 $PID || echo "No process found on port 5001"
          nohup gunicorn -w 3 -b 0.0.0.0:5001 app:app > gunicorn.log 2>&1 &
          echo "Deployment completed successfully!"
          EOF
